---
title: "EE283HW5"
author: "Tatyana Lev"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## base R

```{r}
rm(list=ls())

y <- 7

plot(sin, xlab = expression(sigma[s]^2), ylab = expression(tau), col = "red", lty="dotted", lwd=3, main = bquote(Gamma == .(y)))

text(0.1, 0.4, bquote(Gamma == .(y)))

# DIDN'T WORK TO MAKE ONLY THE X-AXIS SMALLER
#axis(1, "cex.lab" = 0.5) 
#cex.names=0.5
#par(c("cex.lab" = 0.5))
```
#### save as pdf

```{r}
pdf(width=10, height=10, pointsize=18)
plot(sin, xlab = expression(sigma[s]^2), ylab = expression(tau), col = "red", lty="dotted", lwd=3, main = bquote(Gamma == .(y)))
text(0.1, 0.4, bquote(Gamma == .(y)))
dev.off()
```

#### save as tiff

```{r}
tiff(width=10, height=10, units="in", res = 300, pointsize=18)
plot(sin, xlab = expression(sigma[s]^2), ylab = expression(tau), col = "red", lty="dotted", lwd=3, main = bquote(Gamma == .(y)))
text(0.1, 0.4, bquote(Gamma == .(y)))
dev.off()
```

#### save as png - 1: 72 dpi

```{r}
png(width=10, height=10, units="in", res = 72, pointsize=18)
plot(sin, xlab = expression(sigma[s]^2), ylab = expression(tau), col = "red", lty="dotted", lwd=3, main = bquote(Gamma == .(y)))
text(0.1, 0.4, bquote(Gamma == .(y)))
dev.off()
```

#### save as png - 2: 300 dpi

```{r}
png(width=10, height=10, units="in", res = 300, pointsize=18)
plot(sin, xlab = expression(sigma[s]^2), ylab = expression(tau), col = "red", lty="dotted", lwd=3, main = bquote(Gamma == .(y)))
text(0.1, 0.4, bquote(Gamma == .(y)))
dev.off()
```

## ggplot

```{r}
library(ggplot2)

y = 7

data(mtcars)
p <- ggplot(mtcars, aes(x=cyl, y = mpg)) + geom_point() + ylab(expression(tau)) + xlab(expression(sigma[s]^2)) + geom_point(color="red", size=3) + ggtitle(bquote(Gamma == .(y))) + theme(text = element_text(size = 18)) + theme(axis.title.x = element_text(size = 9)) + annotate("text", x=0.1, y=0.4, label= bquote(Gamma == .(y)))

p
```

```{r}
library(ggpubr)
ggarrange(p, p,
          ncol = 2, nrow = 1)
```


```{r}
ggarrange(p, p, p, p,
          ncol = 2, nrow = 2)
```

#### save pdf

```{r}
ggsave(filename = "plot.pdf", plot = p, device = "pdf", width = 10, height = 10, units = "in", dpi = 300)
```

#### save tiff

```{r}
ggsave(filename = "plot.tiff", plot = p + theme(text = element_text(size = 18)) + theme(axis.title.x = element_text(size = 9)), device = "pdf", width = 10, height = 10, units = "in", dpi = 300)
```

#### save png 1: 72 dpi

```{r}
ggsave(filename = "plot.png", plot = p, device = "png", width = 10, height = 10, units = "in", dpi = 72)
```


#### save png 2: 300 dpi

```{r}
ggsave(filename = "plot.png", plot = p, device = "png", width = 10, height = 10, units = "in", dpi = 300)
```

